### ISSUE TITLE
Schema.org JobPosting

### ISSUE THREAD

**Issue by danbri** [lukasz-madon/json-job#1]
Hi. Have you seen the JobPosting schema we have over at schema.org? It should work fine in JSON (via JSON-LD) too. 
- http://schema.org/JobPosting
- http://www.whitehouse.gov/blog/2011/11/07/open-innovation-heroes-introducing-veterans-job-bank
- http://blog.schema.org/2011/11/schemaorg-support-for-job-postings.html
- https://github.com/schemaorg/schemaorg/issues (issue tracker for suggestions, bugs)

I don't mean to discourage this initiative but the JobPosting schema (more in Microdata than JSON-LD but it's the vocabulary that counts) is on quite a lot of sites now - see e.g. https://www.google.com/cse/publicurl?cx=013484121852858951051:dge0pjzsolq for a test search of pages using it.

**Comment by lukasz-madon** [comment]
I have seen the project. The problem is there are a lot of useful properties missing e.g. remote work and contributing is harder.

**Comment by danbri** [comment]
ok!
