### ISSUE TITLE
Non-camelCase attributes prevent normal direct attribute access in JavaScript

### ISSUE THREAD

**Issue by rwe** [lukasz-madon/json-job#2]
When loaded into JavaScript, a job posting object "foo" can have some attributes index directly (`foo.company`) but some require indexing in (`foo["remote-friendly"]`). If attributes used camelCase uniformly, one could access all attributes that way, e.g. `foo.remoteFriendly`.

This currently applies to:
- `remote-friendly`
- `salary-range`

**Comment by lukasz-madon** [comment]
:+1:
