### ISSUE TITLE
"errros":null

### ISSUE THREAD

**Issue by razbakov** [lukasz-madon/json-job#5]
There is typo in "errros" in [README](https://github.com/lukasz-madon/json-job/blob/master/README.md)

I didn't check if there is the same mistake in API response.

**Comment by lukasz-madon** [comment]
heroku is in the exact state that Github. I'll fix it.

For future I'd would be less work for both of us if you just submit PR (just click the file and pencil button)

**Comment by razbakov** [comment]
check https://github.com/lukasz-madon/json-job/pull/16 and https://github.com/lukasz-madon/json-job/pull/17
